### ISSUE TITLE
Add GUI!

### ISSUE THREAD

**Issue by Jothin-kumar** [SanjayKandel/password_manager#9]
I would like to add GUI support to password manager using tkinter. Please assign me. Thank you!

**Comment by Jothin-kumar** [comment]
@SanjayKandel The GUI is almost complete! I will open a PR after adding the following features:
 - Scrollbar.
 - Copy password.
 - Show or hide password.

**Comment by SanjayKandel** [comment]
Sounds great. I'll wait for your PR.

**Comment by Jothin-kumar** [comment]
@SanjayKandel Done! #11

**Comment by SanjayKandel** [comment]
Hey @Jothin-kumar there were some issues with your PR.
Here are some things you should consider changing:
1. Don't integrate the GUI file with pass_generator keep them separate, so user can have option for terminal based application as well as GUI.
2.  In addition to that you can use random password generator function(pass_generator file) in your GUI to randomly generate strong password rather than.
3. If you don't like the second option you can add some type of password check for password strength.
Feel free to add extra features but do consider 1st option.

**Comment by SanjayKandel** [comment]
If you could just wait for 1 day i'm changing the core structure of the project.
I am working on following file structure:
**/apps**
  _client.py_
_model.py_
_pass_generator.py_


Folder **/apps** will contain
1. client.py    -> terminal app
2. Gui.py        -> your gui app
3. Flask app  -> web app based on flask currently im working on this.

_model.py_ will maintain our database

_pass_generator.py_ this will be core of the  project responsible for cryptography related stuff.

**Comment by Jothin-kumar** [comment]
> Hey @Jothin-kumar there were some issues with your PR.
> Here are some things you should consider changing:
> 1. Don't integrate the GUI file with pass_generator keep them separate, so user can have option for terminal based application as well as GUI.
> 2.  In addition to that you can use random password generator function(pass_generator file) in your GUI to randomly generate strong password rather than.
> 3. If you don't like the second option you can add some type of password check for password strength.
> Feel free to add extra features but do consider 1st option.  

@SanjayKandel actually, I programmed the password manager to automatically generate a secure password if the user leaves the password field blank. This will allow the user to set their own longer password which might be more secure than the auto generated one. I will consider 3rd option. Let me program it to send warning messages when less secure password are used.

**Comment by Jothin-kumar** [comment]
> If you could just wait for 1 day i'm changing the core structure of the project.
> I am working on following file structure:
> **/apps**
>  &nbsp;&nbsp;&nbsp; _client.py_
> **_model.py_**
> **_pass_generator.py_**
> 
> 
> Folder **/apps** will contain
> 1. client.py    -> terminal app
> 2. Gui.py        -> your gui app
> 3. Flask app  -> web app based on flask currently im working on this.
> 
> _model.py_ will maintain our database
> 
> _pass_generator.py_ this will be core of the  project responsible for cryptography related stuff.
> 
> 

@SanjayKandel great! That would definitely make my work easier. I can help you to make a flask app if you want.

**Comment by SanjayKandel** [comment]
@Jothin-kumar I have made the changes you can make the GUI. If you wish to implement the flask app then go ahead.

**Comment by Jothin-kumar** [comment]
> @Jothin-kumar I have made the changes you can make the GUI. If you wish to implement the flask app then go ahead.

Yeah, I would implement both GUI and flask app soon!

**Comment by SanjayKandel** [comment]
Ok
